name: Rust

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Clippy and Unit Tests
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-workspaces: |
            . -> target
            ./examples/batchmap-cat -> target
            ./examples/batchmap-flatmap -> target
            ./examples/map-cat -> target
            ./examples/map-tickgen-serde -> target
            ./examples/mapt-event-time-filter -> target
            ./examples/reduce-counter -> target
            ./examples/sideinput -> target
            ./examples/sideinput/udf -> target
            ./examples/simple-source -> target
            ./examples/sink-log -> target
            ./examples/source-transformer-now -> target

      - name: Configure sccache
        run: |
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
          echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.5

      - name: Install dependencies
        run: sudo apt-get install -y protobuf-compiler

      - name: Lint
        run: make lint

      - name: Run tests
        run: make test

      - name: Dry run Cargo Publish
        run: cargo publish --dry-run
