name: Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
      - dev-release*

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Publish to crates.io
    runs-on: ubuntu-24.04
    timeout-minutes: 12
    # run workflow only on numaproj/numaflow-rs repository
    if: ${{ github.repository }} == "numaproj/numaflow-rs"
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install dependencies
        run: sudo apt-get install -y protobuf-compiler

      - name: Lint
        run: make lint

      - name: Run tests
        run: make test

      - name: Cargo login
        run: cargo login ${{ secrets.CARGO_PUBLISH }}

      - name: Dry run Cargo Publish
        run: cargo publish --dry-run
