name: Release

on:
  release:
    types: [ created ]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Publish to crates.io
    runs-on: ubuntu-24.04
    timeout-minutes: 12
    if: ${{ github.repository }} == "BulkBeing/numaflow-rs"
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: false

      - name: Install dependencies
        run: sudo apt-get install -y protobuf-compiler


      - name: Dry run Cargo Publish
        run: CARGO_REGISTRY_TOKEN=${{ secrets.CARGO_PUBLISH }} cargo publish --dry-run
